import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/redux/provider";
import ToastComponent from "@/components/ToastComponent";
import SessionProvider from "../components/SessionProvider";
import { Suspense } from "react";
import Loading from "./(root)/user/personal/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Courses APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <Providers>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </Providers>
        <ToastComponent />
      </body>
    </html>
  );
}
